# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.hanerma.core.rpc import hanerma_hub_pb2 as src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/hanerma/core/rpc/hanerma_hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CUAHubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamComputerUse = channel.stream_stream(
                '/hanerma.rpc.CUAHub/StreamComputerUse',
                request_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.AgentState.SerializeToString,
                response_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HubCommand.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/hanerma.rpc.CUAHub/Click',
                request_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ClickRequest.SerializeToString,
                response_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/hanerma.rpc.CUAHub/TypeText',
                request_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.TypeRequest.SerializeToString,
                response_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.TakeScreenshot = channel.unary_unary(
                '/hanerma.rpc.CUAHub/TakeScreenshot',
                request_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hanerma.rpc.CUAHub/Heartbeat',
                request_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPong.FromString,
                _registered_method=True)


class CUAHubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamComputerUse(self, request_iterator, context):
        """Bidirectional stream for continuous screen state and action commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Unary RPCs for direct invocation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """System Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CUAHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamComputerUse': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamComputerUse,
                    request_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.AgentState.FromString,
                    response_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HubCommand.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ClickRequest.FromString,
                    response_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.TypeRequest.FromString,
                    response_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.SerializeToString,
            ),
            'TakeScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeScreenshot,
                    request_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotRequest.FromString,
                    response_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPing.FromString,
                    response_serializer=src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hanerma.rpc.CUAHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hanerma.rpc.CUAHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CUAHub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamComputerUse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hanerma.rpc.CUAHub/StreamComputerUse',
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.AgentState.SerializeToString,
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HubCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hanerma.rpc.CUAHub/Click',
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ClickRequest.SerializeToString,
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hanerma.rpc.CUAHub/TypeText',
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.TypeRequest.SerializeToString,
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hanerma.rpc.CUAHub/TakeScreenshot',
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotRequest.SerializeToString,
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hanerma.rpc.CUAHub/Heartbeat',
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPing.SerializeToString,
            src_dot_hanerma_dot_core_dot_rpc_dot_hanerma__hub__pb2.HeartbeatPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
