# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/hanerma/core/rpc/hanerma_hub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/hanerma/core/rpc/hanerma_hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&src/hanerma/core/rpc/hanerma_hub.proto\x12\x0bhanerma.rpc\"W\n\nAgentState\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05vm_ip\x18\x02 \x01(\t\x12\x15\n\rscreen_buffer\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"K\n\nHubCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"6\n\x0c\x43lickRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"-\n\x0bTypeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"%\n\x11ScreenshotRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"8\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"P\n\x12ScreenshotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x15\n\rerror_message\x18\x03 \x01(\t\"4\n\rHeartbeatPing\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"%\n\rHeartbeatPong\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xf9\x02\n\x06\x43UAHub\x12K\n\x11StreamComputerUse\x12\x17.hanerma.rpc.AgentState\x1a\x17.hanerma.rpc.HubCommand\"\x00(\x01\x30\x01\x12\x41\n\x05\x43lick\x12\x19.hanerma.rpc.ClickRequest\x1a\x1b.hanerma.rpc.ActionResponse\"\x00\x12\x43\n\x08TypeText\x12\x18.hanerma.rpc.TypeRequest\x1a\x1b.hanerma.rpc.ActionResponse\"\x00\x12S\n\x0eTakeScreenshot\x12\x1e.hanerma.rpc.ScreenshotRequest\x1a\x1f.hanerma.rpc.ScreenshotResponse\"\x00\x12\x45\n\tHeartbeat\x12\x1a.hanerma.rpc.HeartbeatPing\x1a\x1a.hanerma.rpc.HeartbeatPong\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.hanerma.core.rpc.hanerma_hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSTATE']._serialized_start=55
  _globals['_AGENTSTATE']._serialized_end=142
  _globals['_HUBCOMMAND']._serialized_start=144
  _globals['_HUBCOMMAND']._serialized_end=219
  _globals['_CLICKREQUEST']._serialized_start=221
  _globals['_CLICKREQUEST']._serialized_end=275
  _globals['_TYPEREQUEST']._serialized_start=277
  _globals['_TYPEREQUEST']._serialized_end=322
  _globals['_SCREENSHOTREQUEST']._serialized_start=324
  _globals['_SCREENSHOTREQUEST']._serialized_end=361
  _globals['_ACTIONRESPONSE']._serialized_start=363
  _globals['_ACTIONRESPONSE']._serialized_end=419
  _globals['_SCREENSHOTRESPONSE']._serialized_start=421
  _globals['_SCREENSHOTRESPONSE']._serialized_end=501
  _globals['_HEARTBEATPING']._serialized_start=503
  _globals['_HEARTBEATPING']._serialized_end=555
  _globals['_HEARTBEATPONG']._serialized_start=557
  _globals['_HEARTBEATPONG']._serialized_end=594
  _globals['_CUAHUB']._serialized_start=597
  _globals['_CUAHUB']._serialized_end=974
# @@protoc_insertion_point(module_scope)
